=== yuusuke1818/localosaki/localosaki-web/src/main/webapp/WEB-INF/access/operation.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
    PUBLIC ID: osol-operation
    SYSTEM ID: "operation.dtd"
-->
<!-- 操作ロールリスト -->
<!ELEMENT OperationList (Operation*)>
    <!-- 操作企業情報[企業種別(0 or 1), 権限種別(0 or 1), 担当者権限コード(0 or 1)] -->
    <!ELEMENT Operation (CorpType?, AuthorityType?, AuthorityCd?)>
    <!-- ロールキー(必須) -->
    <!ATTLIST Operation Key ID #REQUIRED>
    <!-- ロール名(必須) -->
    <!ATTLIST Operation Name CDATA #REQUIRED>
        <!-- 企業種別 -->
        <!ELEMENT CorpType (#PCDATA)>
            <!-- 企業種別の値 -->
            <!ENTITY 大崎電気工業 "0">
            <!ENTITY パートナー企業 "1">
            <!ENTITY メンテナンス企業 "2">
            <!ENTITY 契約企業 "3">
        <!-- 権限種別 -->
        <!ELEMENT AuthorityType (#PCDATA)>
            <!-- 権限種別の値 -->
            <!ENTITY 管理担当 "0">
            <!ENTITY 建物担当 "1">
        <!-- 担当者権限コード -->
        <!ELEMENT AuthorityCd (#PCDATA)>
            <!-- 担当者権限コードの値 -->
            <!ENTITY 管理者権限 "001">
            <!ENTITY 建物テナント設備管理 "002">
            <!ENTITY メンテナンス管理 "003">
            <!ENTITY エネルギー目標入力 "004">
            <!ENTITY エネルギー使用量入力 "005">
            <!ENTITY 集計分析 "006">
            <!ENTITY 計画履行入力 "007">
            <!ENTITY サイネージ管理 "008">
            <!ENTITY エネルギー使用状況確認 "009">
            <!ENTITY 機器制御 "010">

=== yuusuke1818/localosaki/localosaki-web/src/main/webapp/WEB-INF/access/operation.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE OperationList SYSTEM "operation.dtd">
<OperationList>
    <Operation Key="CORP" Name="企業担当">
        <AuthorityType>&管理担当;</AuthorityType>
    </Operation>
    <Operation Key="BUILDING" Name="建物担当">
        <AuthorityType>&建物担当;</AuthorityType>
    </Operation>
    <Operation Key="BUILDING_ON_FACILITY" Name="建物担当：設備管理">
        <AuthorityType>&建物担当;</AuthorityType>
        <AuthorityCd>&建物テナント設備管理;</AuthorityCd>
    </Operation>
    <Operation Key="BUILDING_ON_MAINTENANCE" Name="建物担当：メンテナンス管理">
        <AuthorityType>&建物担当;</AuthorityType>
        <AuthorityCd>&メンテナンス管理;</AuthorityCd>
    </Operation>
    <Operation Key="BUILDING_ON_ENEINPUTTARGET" Name="建物担当：エネルギー目標入力">
        <AuthorityType>&建物担当;</AuthorityType>
        <AuthorityCd>&エネルギー目標入力;</AuthorityCd>
    </Operation>
    <Operation Key="BUILDING_ON_ENEINPUTUSE" Name="建物担当：エネルギー使用量入力">
        <AuthorityType>&建物担当;</AuthorityType>
        <AuthorityCd>&エネルギー使用量入力;</AuthorityCd>
    </Operation>
    <Operation Key="BUILDING_ON_ANALYSIS" Name="建物担当：集計分析">
        <AuthorityType>&建物担当;</AuthorityType>
        <AuthorityCd>&集計分析;</AuthorityCd>
    </Operation>
    <Operation Key="BUILDING_ON_PLANDO" Name="建物担当：計画履行入力">
        <AuthorityType>&建物担当;</AuthorityType>
        <AuthorityCd>&計画履行入力;</AuthorityCd>
    </Operation>
    <Operation Key="BUILDING_ON_SIGNAGE" Name="建物担当：サイネージ管理">
        <AuthorityType>&建物担当;</AuthorityType>
        <AuthorityCd>&サイネージ管理;</AuthorityCd>
    </Operation>
    <Operation Key="BUILDING_ON_DEMAND" Name="建物担当：エネルギー使用状況確認">
        <AuthorityType>&建物担当;</AuthorityType>
        <AuthorityCd>&エネルギー使用状況確認;</AuthorityCd>
    </Operation>
    <Operation Key="BUILDING_ON_DEVCONTROL" Name="建物担当：機器制御">
        <AuthorityType>&建物担当;</AuthorityType>
        <AuthorityCd>&機器制御;</AuthorityCd>
    </Operation>
</OperationList>
