=== yuusuke1818/localosaki/localosaki-web/src/main/webapp/WEB-INF/access/rolegroup.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
    PUBLIC ID: osol-rolegroup
    SYSTEM ID: "rolegroup.dtd"
-->
<!-- RoleGroupリスト -->
<!ELEMENT RoleGroupList (RoleGroup*)>
    <!-- RoleGroup  -->
    <!ELEMENT RoleGroup (Role+)>
        <!-- ロールキー -->
        <!ELEMENT Role (#PCDATA)>
<!-- Key(ユニーク,必須) -->
<!ATTLIST RoleGroup Key ID #REQUIRED>
<!-- Name(必須) -->
<!ATTLIST RoleGroup Name CDATA #REQUIRED>

=== yuusuke1818/localosaki/localosaki-web/src/main/webapp/WEB-INF/access/rolegroup.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE RoleGroupList SYSTEM "rolegroup.dtd">
<RoleGroupList>
    <!-- 管理者 -->
    <RoleGroup Key="Administrator" Name="管理者" >
        <Role>OSAKI_FOR_CORP</Role>
        <Role>PARTNER_FOR_CORP</Role>
        <Role>MAINTENANCE_ON_ADMIN</Role>
        <Role>CONTRACT_ON_ADMIN</Role>
    </RoleGroup>
    <!-- 大崎またはパートナー企業担当 -->
    <RoleGroup Key="OsakiOrPartnerCorp" Name="大崎またはパートナー企業担当" >
        <Role>OSAKI</Role>
        <Role>PARTNER_FOR_CORP</Role>
    </RoleGroup>
</RoleGroupList>
